name: Deploy para S3

description: >-
  Realiza o upload do arquivo .cmpkg gerado para o bucket S3, baixando o último release publicado do repositório e exportando o caminho do arquivo .cmpkg encontrado.

# Entradas obrigatórias para autenticação e upload
inputs:
  repo_key:
    description: Chave do repositório para autenticação
    required: true
  nexus_username:
    description: Usuário do Nexus
    required: true
  nexus_password:
    description: Senha do Nexus
    required: true
  aws_access_key_id:
    description: AWS Access Key ID
    required: true
  aws_secret_access_key:
    description: AWS Secret Access Key
    required: true

# Outputs para reutilização em outros jobs
outputs:
  caminho-cmpkg:
    description: Caminho completo do arquivo .cmpkg baixado
    value: ${{ steps.arquivo.outputs.caminho-cmpkg }}
  nome-cmpkg:
    description: Nome do arquivo .cmpkg baixado
    value: ${{ steps.arquivo.outputs.nome-cmpkg }}

runs:
  using: composite
  steps:
    # Baixa todos os arquivos do último release publicado (inclui .cmpkg e .dat)
    - name: Baixar o CMPKG do ultimo release
      id: download
      uses: robinraju/release-downloader@v1
      with:
        latest: true
        fileName: "*"
        tarBall: false
        zipBall: false
        out-file-path: ./pacote
        token: ${{ github.token }}

    # Lista os arquivos baixados para conferência
    - name: Listar arquivos baixados
      shell: bash
      run: ls -l ./pacote

    # Captura o caminho e o nome do arquivo .cmpkg baixado e exporta como outputs
    - name: Obter o nome do CMPKG
      id: arquivo
      shell: bash
      run: |
        caminho=$(ls ./pacote/*.cmpkg | head -n 1)
        nome=$(basename "$caminho")
        echo "caminho-cmpkg=$caminho" >> $GITHUB_OUTPUT
        echo "nome-cmpkg=$nome" >> $GITHUB_OUTPUT

    # Realiza o upload do arquivo .cmpkg para o bucket S3 usando o action customizado
    - name: Deploy para S3
      id: deploy-s3
      uses: ColibriAgile/build-tools/.github/actions/s3-uploader@master
      with:
        cmpkg: ${{ steps.arquivo.outputs.caminho-cmpkg }}
        stage: false
        repo_key: ${{ inputs.repo_key }}
        nexus_username: ${{ inputs.nexus_username }}
        nexus_password: ${{ inputs.nexus_password }}
        aws_access_key_id: ${{ inputs.aws_access_key_id }}
        aws_secret_access_key: ${{ inputs.aws_secret_access_key }}
