name: Empacotar scripts
# Empacotar scripts com o BuildTools
description: >-
  Empacota scripts utilizando o BuildTools. Baixa automaticamente a versão mais recente do BuildTools.exe do repositório ColibriAgile/build-tools e executa o empacotamento de scripts, recebendo como parâmetros a pasta de origem, a pasta de destino e opções extras. Ideal para automatizar o empacotamento de scripts em pipelines CI/CD.

on:
  workflow_call:
    inputs:
      pasta-origem:
        required: true
        type: string
      pasta-destino:
        required: true
        type: string
      extras:
        required: false
        type: string

jobs:
  empacotar-scripts:
    if: github.event_name == 'workflow_call'
    runs-on: windows-latest
    steps:
      - name: Baixar buildTools.exe do GitHub Releases
        uses: robinraju/release-downloader@v1
        with:
          repository: ColibriAgile/build-tools
          latest: true
          fileName: BuildTools.exe
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Executar buildTools.exe (empacotar-scripts)
        shell: pwsh
        run: |
          try {
            .\buildTools.exe empacotar_scripts 
              --pasta "${{ inputs.pasta-origem }}" 
              --saida "${{ inputs.pasta-destino }}" 
              ${{ inputs.extras }}
          } catch {
            Write-Error "Erro ao executar buildTools.exe: $_"
            exit 1
          }
