name: Build e Versão

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fetch all history for GitVersion
      run: git fetch --prune --unshallow

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.2.1
      with:
        versionSpec: '5.x'

    - name: Run GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v3.2.1

    - name: Show calculated version
      run: |
        echo GitVersion: ${{ steps.gitversion.outputs.fullSemVer }}

    - name: Restore dependencies
      run: dotnet restore BuildTools/BuildTools.csproj

    - name: Publish win-x64
      run: |
        dotnet publish BuildTools/BuildTools.csproj `
          -c Release `
          -r win-x64 `
          /p:Version=${{ steps.gitversion.outputs.fullSemVer }}

    - name: List publish folder before zip
      if: success()
      run: dir BuildTools/bin/Release/net9.0/win-x64/publish

    - name: Publish zip artifact
      if: success()
      run: |
        cd BuildTools/bin/Release/net9.0/win-x64/publish
        del BuildTools-*.zip 2>NUL
        7z a BuildTools-${{ steps.gitversion.outputs.assemblySemVer }}.win-x64.zip .\*

    - name: Upload zip to workflow artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: BuildTools.win-64
        path: BuildTools/bin/Release/net9.0/win-x64/publish/BuildTools-${{ steps.gitversion.outputs.assemblySemVer }}.win-x64.zip
        if-no-files-found: ignore
        retention-days: 2