# Este workflow agora é reutilizável e pode ser chamado de outros repositórios
name: Deploy

on:
  workflow_call:
    secrets:
      REPO_KEY:
        required: true
      NEXUS_USERNAME:
        required: true
      NEXUS_PASSWORD:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Baixa todos os arquivos do último release publicado (inclui .cmpkg e .dat)
      - name: Baixar o CMPKG do ultimo release
        id: download
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: "*"
          tarBall: false
          zipBall: false
          out-file-path: ./pacote
          token: ${{ secrets.GITHUB_TOKEN }}

      # Lista os arquivos baixados para conferência
      - name: Listar arquivos baixados
        run: ls -l ./pacote

      # Captura o nome do arquivo .cmpkg baixado e exporta para uso nos próximos passos
      - name: Obter o nome do CMPKG
        id: arquivo
        run: |
          echo "nome=$(ls ./pacote/*.cmpkg | head -n 1)" >> $GITHUB_OUTPUT

      # Realiza o upload do arquivo .cmpkg para o bucket S3 usando o action customizado
      - name: Deploy para S3
        id: deploy-s3
        uses: ColibriAgile/build-tools/.github/actions/s3-uploader@master
        with:
          cmpkg: ${{ steps.arquivo.outputs.nome }}
          stage: false
          repo_key: ${{ secrets.REPO_KEY }}
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
