name: Empacotar scripts
# Empacotar scripts com o BuildTools

on:
  workflow_call:
    inputs:
      pasta-origem:
        required: true
        type: string
      pasta-destino:
        required: true
        type: string
      extras:
        required: false
        type: string

jobs:
  empacotar-scripts:
    if: github.event_name == 'workflow_call'
    runs-on: windows-latest
    steps:
      - name: Baixar buildTools.exe do GitHub Releases
        uses: dawidd6/action-download-release@v3
        with:
          repository: usuario/build-tools
          tag: latest-production
          file: BuildTools.exe
          out-file-path: buildTools.exe
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Executar buildTools.exe (empacotar-scripts)
        run: >
          .\buildTools.exe empacotar_scripts
          --pasta "${{ inputs.pasta-origem }}"
          --saida "${{ inputs.pasta-destino }}"
          ${{ inputs.extras }}
