# Limpa execuções antigas do workflow
name: Limpar

on:
  workflow_dispatch:
    inputs:
      keep_last:
        description: 'Quantidade de execuções para manter'
        required: true
        default: '15'
        
  schedule:
    - cron: '0 0 */2 * *'

permissions:
  actions: write
  contents: read

jobs:
  limpar-execucoes:
    uses: ColibriAgile/github-actions/.github/workflows/clean_runs.yml@main
    with:
      keep_last: ${{ fromJSON(github.event.inputs.keep_last) }}
    secrets: inherit