name: Testes

on:
  workflow_dispatch:  
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore BuildTools.Testes/BuildTools.Testes.csproj

    - name: Test with coverage
      run: |
        dotnet test BuildTools.Testes/BuildTools.Testes.csproj `
          --verbosity normal `
          --collect:"XPlat Code Coverage" `
          --logger trx `
          --results-directory TestResults

    - name: List test results (debug)
      if: always()
      run: |
        echo "Conteúdo do diretório TestResults:"
        dir TestResults -Recurse
        echo "Procurando arquivos .trx:"
        Get-ChildItem -Path . -Filter "*.trx" -Recurse | Select-Object FullName
        echo "Procurando arquivos de coverage:"
        Get-ChildItem -Path . -Filter "coverage.cobertura.xml" -Recurse | Select-Object FullName

    - name: Publish test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: TestResults/**/*.trx
        if-no-files-found: warn

    - name: Publish code coverage
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage
        path: TestResults/**/coverage.cobertura.xml
        if-no-files-found: warn

    - name: Upload coverage reports to Codecov
      if: success()
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: ColibriAgile/build-tools
        directory: ./TestResults/
        fail_ci_if_error: false
        files: ./TestResults/**/coverage.cobertura.xml
        flags: unittests
        verbose: true

    - name: Publish Test Results to GitHub
      if: always()
      uses: dorny/test-reporter@v2
      with:
        name: .NET Tests
        path: TestResults/**/*.trx
        reporter: dotnet-trx
        fail-on-error: false